<?php
  $bgm_weapon['sword']['desc']               = 'This is a sword of ridiculous proportions. If you\'re not as powerful as a little pwny, I don\'t know how you\'re even carrying it. Needless to say, it\'s both sharp and heavy, and this is very bad for anybody you come across.';
  $bgm_weapon['sword']['attack1']['desc']    = 'With a mighty arcing swing, you bisect your puny opponent. Skilled swordsmen have been known to carve intricate patterns from their opponents, and the Meat Museum on the outskirts of town showcases the finest of these works of art. This attack works best if you\'re strong, and the only chance the opponent has is to agilely move out of your way.';
  $bgm_weapon['sword']['attack2']['desc']    = 'This is a manoeuvre that uses your great big sword to make a new orifice in someone. It\'s like rape, but more violent. And with a sword. This attack requires you to be agile, but if the opponent is lucky enough they can move out of the way. If they do get impaled, they take a lot of damage. You know, new orifice.';

  $bgm_weapon['gunchuck']['desc']            = 'Most people can\'t really decide if they like kung fu movies or John Woo movies better. Well, we\'ve combined them into one awesome whole. Take two guns, tie them together, and what do you get? Gunchucks! Now you can shoot people and hit them at the same time.';
  $bgm_weapon['gunchuck']['attack1']['desc'] = 'This attack takes advantage of the fact that you\'re holding two guns. That\'s twice the bullet output of a normal gunman! However, because that\'s so many bullets, you would have to be lucky to make any of them hit. And a strong opponent will just block.';
  $bgm_weapon['gunchuck']['attack2']['desc'] = 'With the mightiness of gunchucks, you can swing them around and hit everybody nearby, occasionally firing sexy pieces of metal into them. This attack does more damage if you\'re strong, and an intelligent opponent knows the gunchuck patterns well enough to avoid being hit. Or shot. Mostly. Combining the beating and shooting tends to deal more damage than usual.';

  $bgm_weapon['scissor']['desc']             = 'If you still have both eyes, your mother told you not to run with scissors. The trick, though, is to run into other people with them. That\'s some stabby goodness!';
  $bgm_weapon['scissor']['attack1']['desc']  = 'If you run with scissors, somebody\'s going to get hurt. If you\'re agile, it won\'t be you. Intelligent people know not to be near a guy running around with scissors, though.';
  $bgm_weapon['scissor']['attack2']['desc']  = 'Yeah. Just like in that video. Whoever you hit with this is going to have to go to the fucking hospital and get stitches. You don\'t really need stitches unless you\'ve been heavily damaged, though. The proper arc to land scissors in someone\'s arm requires great intelligence, and a strong opponent is immune to bullets. I mean, thrown scissors.';

  $bgm_weapon['phone']['desc']               = 'Most people using the internet now weren\'t alive in the 80s, so let me explain: phones were big back then. Bigger than your mom, if you can believe that. As such, they make for great bludgeoning weapons. Just don\'t try to talk on them. That\'s like a dial-up connection for your voice.';
  $bgm_weapon['phone']['attack1']['desc']    = 'You know how ring tones are annoying now? Imagine them badly-encoded into .mid format, then played on crappy 80s speakers. Yeah, it makes people die. However, you have to be lucky enough for someone to call you while an enemy is nearby, and intelligent people will just kick you in the face.';
  $bgm_weapon['phone']['attack2']['desc']    = 'Since the phone is so big, the natural thing to do is hit people with it. Unfortunately, it\'s too big to actually pick up. Thus, you have to design a complex catapult to launch it at your opponent. This requires that you be very intelligent, and hope the opponent is unlucky enough to walk onto the big X you painted on the street. Unfortunately, most people are not built to take a shot from a catapult. This attack thus tends to do extra damage if it hits somebody.';


  $bgm_race['anthro']['desc']        = 'Usually just called furries, this is a cross between a person and an animal. Usually. I did know that one guy who was an anthropomorphic toaster person. Furries can usually be distracted by bits of string, or a well-thrown frisbee.';
  
  $bgm_race['demi']['desc']          = 'This is a person that\'s half-Asian, half-something else. Like Blade, they have all of an Asian\'s strengths, but none of their weaknesses. Demi-Asian\'s are well-known for their math and martial arts skills, and are powered by teriyaki.';
  
  $bgm_race['dog']['desc']           = 'Finally having gotten better technology than the 80s, did we develop a smaller cell phone? No! Then where would people get their weapons? We made a robot/dog hybrid. Being a new breed of creature, cybernetic dogs have had to look to popular culture for role models. Most choose Arnold Schwartzenneger or Kano.';
  
  $bgm_race['pwny']['desc']          = 'This is what happens when you take a normal horse and infuse it with the essense of badass. And lightning. Little Pwnies are well-known for their ability to shoot lightning from their nostrils. These pwnies don\'t like being ridden - they ride you, on the Pain Train.';
  

  $bgm_class['thief']['desc']                   = 'Thieves are just like normal people, except they steal things. And stab you. Not always in that order.';
  $bgm_class['thief']['attack1']['desc']        = 'What\'s that, in the shadows? Oh no! It\'s a thief! It seems your luck has run out, and now he\'s going to use his strength to beat the money out of you. Obviously, this earns the thief extra bling.';
  $bgm_class['thief']['attack2']['desc']        = 'Lo, there seems to be a blade lodged in your meaty abdomen. It seems that a strong thief has gotten you from behind, and you weren\'t strong enough to resist it. Thieves brag about their backstabby prowess, and each successful assault tends to increase their fame.';
  
  $bgm_class['pirate']['desc']                  = 'Pirates are just like normal thieves, except they ride around on ships. And wear eyepatches. Not always in that order.';
  $bgm_class['pirate']['attack1']['desc']       = 'What\'s that, on the horizon? It seems to be a pirate ship, flying the jolly roger! What an unlucky town. Now pirates are going to use their strength to pillage the village. Sad for you. Bling for them.';
  $bgm_class['pirate']['attack2']['desc']       = 'Lo, there is a pirate standing before ye. Avast! He wants to duel. Get out your sword, and hope you can best him in a contest of strength. The best thing about dueling is that it earns a pirate fame and admiration for winning.';
  
  $bgm_class['assassin']['desc']                = 'Assassins kill people. Usually for money. Sometimes they just don\'t like people, though. And they never want ice in their drink. They\'ll kill people over that, too.';
  $bgm_class['assassin']['attack1']['desc']     = 'What\'s that, in the rafters? Oh no! It\'s an assassin! He leaps down to get his stab on. You\'d better hope you\'re strong enough to resist his agile blade moves. Inexplicably, the assassin has gotten away before you can identify him.';
  $bgm_class['assassin']['attack2']['desc']     = 'Lo, your hit points seem to be missing. What happened? There must have been an assassin, and he was much more agile than you. Touch of Death is a difficult manouevre to master, and assassins who can use it earn bonus fame for doing so.';
  
  $bgm_class['ninja']['desc']                   = 'Ninjas are like assassins, but taller. And they kill you faster. That\'s why their name is shorter - you won\'t have time to say "I\'ve been killed by an assassin!"';
  $bgm_class['ninja']['attack1']['desc']        = 'This is like an assassination, but you die quicker. That way the ninja can go badass some more people. It requires the ninja to be agile, and works better on an opponent who is not very strong. Since you die so fast, you are unable to figure out which ninja killed you.';
  $bgm_class['ninja']['attack2']['desc']        = 'When a ninja kills you, you don\'t even notice. That\'s how fast it is. You die, and you thought you still had full health. Ninjas get a lot of fame for being so awesome.';
  
  $bgm_class['salesperson']['desc']             = 'You know how you never want to buy stuff from people who come to your door? This is one of those people. A salesperson is skilled enough to sell ice to an assassin.';
  $bgm_class['salesperson']['attack1']['desc']  = 'Have you ever gone to the fair, and bought something that doesn\'t work when you get it home, even though it worked just fine for the salesperson? That\'s what this trick is all about. He\'s intelligent enough to come up with this scheme, are you intelligent enough to see through it? If you\'re not, he will surely earn some extra bling from the sale.';
  $bgm_class['salesperson']['attack2']['desc']  = 'Knock, knock. Who\'s there? Burglar! Just kidding, it\'s a salesperson. Which is like a burglar, but he leaves behind some useless crap in your house. And still takes your money. He\'s smart enough to find you, and you\'d better hope you\'re agile enough to run away. Since he snuck into your house to leave stuff behind, it\'s hard to know who did it.';
  
  $bgm_class['telemarketer']['desc']            = 'This salesperson used to be limited to calling people during dinner. Now, with so many people wielding giant 80s cell phones, he can call in for the kill at any time! You\'d better hope you have an annoying ring tone.';
  $bgm_class['telemarketer']['attack1']['desc'] = 'With this attack, the telemarketer promises you that his product will always be good. And then it\'s not. And he has some more bling. This attack rarely works on people more intelligent than the telemarketer.';
  $bgm_class['telemarketer']['attack2']['desc'] = 'This attack interrupts your meal, and does more damage based on how much food you haven\'t eaten yet. The telemarketer has to be intelligent enough to figure out when you\'re eating, and he must hope your agility did not allow you to finish your dinner. Mysteriously, caller ID does not function against a Telemarketer.';
  
  $bgm_class['clown']['desc']                   = 'No longer content with frightening small children and carnivaling, now clowns want to go killing. And somehow, despite having big silly shoes and rainbow-coloured hair, they do so very well. Don\'t touch their beepy-sounding nose, though. They hate that.';
  $bgm_class['clown']['attack1']['desc']        = 'If a clown is lucky, he can find random things to juggle. If you\'re not agile, he can juggle things into you. This is usually painful, although sometimes they\'ll throw harmless objects, like knives and acid. Oh, wait. Those hurt. Everybody likes performers, though, and while you\'re getting juggled, he\'s getting famed.';
  $bgm_class['clown']['attack2']['desc']        = 'If a clown isn\'t lucky enough to find random things to juggle, he can make balloon animals. With luck, they will test an opponent\'s luck in battle. That means they go fight. Clowns are nefarious, though. They\'ll fill their balloon animals with dangerous things like chlorine gas and paint. Lead paint. With poison in it. Then he takes your bling, so he can buy more balloons.';
  
  $bgm_class['jester']['desc']                  = 'These are like clowns, but badass. Most jesters are clowns who\'ve had their beepy-sounding nose beeped one too many times. Then they take off the funny rainbow-coloured wig and throw down.';
  $bgm_class['jester']['attack1']['desc']       = 'A jester balances on this ball, requiring great luck to stay on top of it. Then he rolls it over you, requiring great agility to avoid it. Jesters always think this is very funny. It\'s unnerving to be laughed at while you die. That tends to earn them bonus fame, though.';
  $bgm_class['jester']['attack2']['desc']       = 'Jesters love telling jokes. Even when they\'re not in the middle of slaying people. But sometimes, if a jester is very lucky and you are very unlucky, the joke will be deadly. Jesters love this even more than normal jokes. It makes them so happy that they take extra bling from you.';
?>